Feature/topic module tests
amadeusproject/amadeuslms pull request #788
Opened 2021-06-04 23:16 UTC by Zambom

Para testar é necessário que o banco de testes também seja PostgreSQL por conta da função unaccent que verifica o nome nos forms. É só adicionar o parâmetro "TEST" na config do DB do local_settings (aí não precisa aquela parte do if que bormann adicionou pro SQLite)

Ficaria assim:

![image](https://user-images.githubusercontent.com/5719854/120871349-c3176a00-c571-11eb-8a4e-82114dc0bfff.png)

2021-06-21 16:47 UTC, felipebormann requested changes

2021-06-21 16:47 UTC, felipebormann commented on topics/tests/test_views.py
> +        self.assertTemplateUsed(response, "topics/delete.html")
Tem como tu melhorar este teste e checar se de fato quando tu utilizar o Topic.get(slug=self.topic.slug) ele vai retornar None? Assim a gente confirma que de fato a view além de retornar 200, ela realizar a operação no banco.

2021-06-21 16:47 UTC, felipebormann commented on topics/tests/test_views.py
> +"""
Estes testes que estão checando as views estão ok mas acho que além de testar que eles retornaram os  status esperados e os templates usados, a gente tem de checar se o banco está com o estado esperado da ação daquela view.

2021-06-25 03:46 UTC, Zambom commented on topics/tests/test_views.py
> +        self.assertTemplateUsed(response, "topics/delete.html")
Mas esse teste diz respeito ao get, onde ele não realiza a operação de delete ainda, ele só traz a página de confirmação

2021-06-27 03:49 UTC, felipebormann approved these changes

2021-07-01 19:36 UTC, merged